//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeShopWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [Required]
        [RegularExpression(@"^[a-zA-Z]{2,}$")]
        public string FirstName { get; set; }

        [Required]
        [RegularExpression(@"^[a-zA-Z]{2,}$")]
        public string LastName { get; set; }

        [Required]
        [RegularExpression(@"^([0-9]{3})(|-|())([0-9]{3})(|-|())([0-9]{4})$")]
        public string PhoneNumber { get; set; }

        [Required]
        [RegularExpression(@"^\d{5}$")]
        public string ZipCode { get; set; }

        [Required]
        [RegularExpression(@"^([0-9A-z]{5,30})(@[0-9A-z]{5,10}).([0-9A-z]{2,3})$")]
        public string EmailAddress { get; set; }

        [Required]
        [RegularExpression(@"^[A-Za-z0-9]{5,}$")]
        public string Password { get; set; }
    }
}
